In [1]:
import numpy as np
import time as t

test_size = 10000
# create a numpy array of ten thousand random integers between 0 and 1000
rand_nums1 = np.random.rand(test_size)
print(rand_nums1)

[0.87671268 0.87195795 0.88389698 ... 0.19164423 0.48602458 0.35189932]


In [2]:
# create a list of random floats, also 1000 numbers long
rand_nums2 = np.random.rand(test_size)
print(rand_nums2)

[0.97678129 0.16812963 0.6302222  ... 0.14532358 0.14860861 0.24915324]


In [3]:
# cool, now lets compare how long it takes to use a for loop to iterate through these arrays and multiply them all together
start = t.time()
totals = np.zeros([test_size, test_size])
for ii in range(len(rand_nums1)):
    for fi in range(len(rand_nums2)):
        totals[ii][fi] = rand_nums1[ii] * rand_nums2[fi]
end = t.time()

print("for loop took: {} ms".format((end-start) * 1000))


for loop took: 62685.84704399109 ms


In [4]:
print(totals.shape)
print(totals[:10])

(10000, 10000)
[[0.85635654 0.14740138 0.5525238  ... 0.12740703 0.13028705 0.21843581]
 [0.85171221 0.14660197 0.54952726 ... 0.12671605 0.12958046 0.21725115]
 [0.86337403 0.14860927 0.5570515  ... 0.12845108 0.1313547  0.2202258 ]
 ...
 [0.20296897 0.03493627 0.13095619 ... 0.03019732 0.03087993 0.05177247]
 [0.78276905 0.13473504 0.50504493 ... 0.11645883 0.11909137 0.19966542]
 [0.42630114 0.07337759 0.27505077 ... 0.06342424 0.06485794 0.1087391 ]]


In [5]:
# alright, now lets instead use the power of numpy to multiply these arrays instead

# totals = np.zeros([1000, 1000])

start = t.time()
totals1 = np.zeros([test_size, test_size])
# derrr do something...
totals1 = np.outer(rand_nums1, rand_nums2)
print(totals1.shape)
end = t.time()

print("np.dot() took: {} ms".format((end-start) * 1000))

(10000, 10000)
np.dot() took: 513.6580467224121 ms


In [6]:
print(totals1.shape)
print(totals1[:10])
print(totals == totals1)

(10000, 10000)
[[0.85635654 0.14740138 0.5525238  ... 0.12740703 0.13028705 0.21843581]
 [0.85171221 0.14660197 0.54952726 ... 0.12671605 0.12958046 0.21725115]
 [0.86337403 0.14860927 0.5570515  ... 0.12845108 0.1313547  0.2202258 ]
 ...
 [0.20296897 0.03493627 0.13095619 ... 0.03019732 0.03087993 0.05177247]
 [0.78276905 0.13473504 0.50504493 ... 0.11645883 0.11909137 0.19966542]
 [0.42630114 0.07337759 0.27505077 ... 0.06342424 0.06485794 0.1087391 ]]
[[ True  True  True ...  True  True  True]
 [ True  True  True ...  True  True  True]
 [ True  True  True ...  True  True  True]
 ...
 [ True  True  True ...  True  True  True]
 [ True  True  True ...  True  True  True]
 [ True  True  True ...  True  True  True]]


In [7]:
# So wow, yes, we HAVE to use vectors for this sort of this, (ALSO for audio and DSP junk too I assume then...)

In [9]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Use numpy outer() function to multiply every value of array1 by every value of array2
result_of_outer = np.outer(array1, array2)

# Print the result
print(result_of_outer)

result_of_dot = np.dot(array1, array2)

print(result_of_dot)


[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
32
